name: tests-live

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    # Run every Sunday
    - cron: "0 0 * * 0"

jobs:
  build:
    name: Run live tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run live tests
        run: |
          make test-live-cloud
        env:
          LIVE_AZURE_CONTAINER: ${{ secrets.LIVE_AZURE_CONTAINER }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          LIVE_GS_BUCKET: ${{ secrets.LIVE_GS_BUCKET }}
          LIVE_S3_BUCKET: ${{ secrets.LIVE_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CUSTOM_S3_BUCKET: ${{secrets.CUSTOM_S3_BUCKET}}
          CUSTOM_S3_KEY_ID: ${{secrets.CUSTOM_S3_KEY_ID}}
          CUSTOM_S3_SECRET_KEY: ${{secrets.CUSTOM_S3_SECRET_KEY}}
          CUSTOM_S3_ENDPOINT: ${{secrets.CUSTOM_S3_ENDPOINT}}
